CREATE TABLE IF NOT EXISTS `OGPSystem`.`OGP_WARGA_KENDARAAN` (
  `OGP_WARGA_ID` VARCHAR(32) NULL,
  `OGP_WARGA_KENDARAAN_ID` VARCHAR(32) NOT NULL,
  `OGP_WARGA_KENDARAAN_JENIS` VARCHAR(255) NULL,
  `OGP_WARGA_KENDARAAN_NOPLAT` VARCHAR(255) NULL,
  `OGP_WARGA_KENDARAAN_WARNA` VARCHAR(255) NULL,
  `OGP_WARGA_KENDARAAN_MERKTYPE` VARCHAR(255) BINARY NULL,
  PRIMARY KEY (`OGP_WARGA_KENDARAAN_ID`),
  INDEX `fk_OGP_WARGA_KENDARAAN_1_idx` (`OGP_WARGA_ID` ASC),
  CONSTRAINT `fk_OGP_WARGA_KENDARAAN_1`
    FOREIGN KEY (`OGP_WARGA_ID`)
    REFERENCES `OGPSystem`.`OGP_WARGA` (`OGP_WARGA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `OGPSystem`.`OGP_WARGA` (
  `OGP_WARGA_ID` VARCHAR(32) NOT NULL,
  `OGP_WARGA_NIK` VARCHAR(16) NULL,
  `OGP_KK_ID` VARCHAR(16) NULL,
  `OGP_WARGA_NAMA` VARCHAR(255) NULL,
  `OGP_WARGA_ALAMAT` VARCHAR(255) NULL,
  `OGP_WARGA_NEGARA` VARCHAR(255) NULL,
  `OGP_WARGA_KELAMIN` CHAR NULL,
  `OGP_WARGA_TEMPAT_LAHIR` VARCHAR(255) NULL,
  `OGP_WARGA_TGL_LAHIR` DATE NULL,
  `OGP_WARGA_GOLONGANDARAH` CHAR NULL,
  `OGP_WARGA_SUKU` VARCHAR(255) NULL,
  `OGP_WARGA_AGAMA` VARCHAR(255) NULL,
  `OGP_WARGA_PEKERJAAN` VARCHAR(255) NULL,
  `OGP_WARGA_STATUS_PERKAWINAN` CHAR NULL,
  `OGP_WARGA_KEWARGANEGARAAN` VARCHAR(255) NULL,
  `OGP_WARGA_NOPASPOR` VARCHAR(255) NULL,
  `OGP_WARGA_NOKITASKITAP` VARCHAR(255) NULL,
  `OGP_WARGA_NAMAAYAH` VARCHAR(255) NULL,
  `OGP_WARGA_NAMAIBU` VARCHAR(255) NULL,
  `OGP_WARGA_NOTELP` VARCHAR(255) NULL,
  `OGP_WARGA_NOHP` VARCHAR(255) NULL,
  `OGP_WARGA_NOFAX` VARCHAR(255) NULL,
  `OGP_WARGA_EMAIL` VARCHAR(255) NULL,
  `OGP_WARGA_STATUS_KELUARGA` VARCHAR(45) NULL,
  `OGP_WARGA_ASAL_DAERAH` VARCHAR(45) NULL,
  PRIMARY KEY (`OGP_WARGA_ID`),
  CONSTRAINT `fk_OGP_WARGA_1`
    FOREIGN KEY ()
    REFERENCES `OGPSystem`.`OGP_KK` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `OGPSystem`.`OGP_KK` (
  `OGP_KK_ID` INT NOT NULL AUTO_INCREMENT,
  `OGP_RUMAH_ID` VARCHAR(45) NULL,
  `OGP_KK_STATUS_RUMAH` VARCHAR(45) NULL,
  `OGP_KK_PERIODE_AWAL` VARCHAR(45) NULL,
  `OGP_KK_PERIODE_AKHIR` VARCHAR(45) NULL,
  PRIMARY KEY (`OGP_KK_ID`),
  CONSTRAINT `fk_OGP_KK_1`
    FOREIGN KEY ()
    REFERENCES `OGPSystem`.`OGP_RUMAH` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `OGPSystem`.`OGP_WARGA_EMERGENCY` (
  `OGP_WARGA_ID` VARCHAR(32) NULL,
  `OGP_WARGA_EMERGENCY_ID` VARCHAR(32) NOT NULL,
  `OGP_WARGA_EMERGENCY_NAMA` VARCHAR(255) NULL,
  `OGP_WARGA_EMERGENCY_HUBUNGAN` VARCHAR(255) NULL,
  `OGP_WARGA_EMERGENCY_ALAMAT` VARCHAR(255) NULL,
  `OGP_WARGA_EMERGENCY_NOTELP` VARCHAR(255) NULL,
  `OGP_WARGA_EMERGENCY_NOHP` VARCHAR(255) NULL,
  PRIMARY KEY (`OGP_WARGA_EMERGENCY_ID`),
  INDEX `fk_OGP_WARGA_EMERGENCY_1_idx` (`OGP_WARGA_ID` ASC),
  CONSTRAINT `fk_OGP_WARGA_EMERGENCY_1`
    FOREIGN KEY (`OGP_WARGA_ID`)
    REFERENCES `OGPSystem`.`OGP_WARGA` (`OGP_WARGA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `OGPSystem`.`OGP_RUMAH` (
  `OGP_RUMAH_ID` INT NOT NULL,
  `OGP_RUMAH_BLOK` VARCHAR(45) NULL,
  `OGP_RUMAH_RT` VARCHAR(45) NULL,
  `OGP_RUMAH_RW` VARCHAR(45) NULL,
  `OGP_RUMAH_KEL` VARCHAR(45) NULL,
  `OGP_RUMAH_KEC` VARCHAR(45) NULL,
  `OGP_RUMAH_KAB` VARCHAR(45) NULL,
  `OGP_RUMAH_PROV` VARCHAR(45) NULL,
  `OGP_RUMAH_KODEPOS` VARCHAR(45) NULL,
  `OGP_RUMAH_NOP` VARCHAR(45) NULL,
  `OGP_RUMAH_LONG` VARCHAR(45) NULL,
  `OGP_RUMAH_LAT` VARCHAR(45) NULL,
  PRIMARY KEY (`OGP_RUMAH_ID`))
ENGINE = InnoDB
